version: '3.8'

services:
  # The DynamoDB Local database service
  dynamodb:
    # --- START OF CHANGE ---
    # Instead of using a pre-built image, we now build our own custom one
    # that fixes the internal file permissions.
    build:
      context: .
      dockerfile: dynamodb-Dockerfile
    # --- END OF CHANGE ---
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    volumes:
      - ./dynamodb_data:/data # Continue using a bind mount

  # The service to initialize the database
  init:
    build:
      context: .
      dockerfile: dbinit-Dockerfile
    command: ["/app/wait-for-it.sh", "dynamodb", "--", "python", "db_init.py"]
    depends_on:
      - dynamodb

  # The FastAPI application service
  api:
    build:
      context: .
      dockerfile: api-Dockerfile
    ports:
      - "8001:8000"
    environment:
      - IS_LOCAL=true
    depends_on:
      - dynamodb
      - init